name: Build and Push to Harbor

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show docker info and environment
        run: |
          whoami
          groups
          docker info

      - name: Login to Harbor registry
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.bamiland.shop \
            -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=harbor.bamiland.shop/bami-ci-test/myapp:${{ github.sha }}
          docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_TAG


