name: Build and Push to Harbor

on:
  push:
    tags:
      - 'v*'
      - 'v.*'
  
jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew clean build

      - name: Docker Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.bamiland.shop \
            -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=harbor.bamiland.shop/myproject/myimage:${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker Image to Harbor
        run: docker push $IMAGE_TAG



