name: Build and Push to Harbor

on:
  push:
    tags:
      - 'v*'
      - 'v.*'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew clean build

      - name: Docker Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.bamiland.shop \
            -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Debug Ref Info
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"

      - name: Build Docker Image
        run: docker build -t harbor.bamiland.shop/myproject/myimage:${{ github.ref_name }} .

      - name: Push Docker Image to Harbor
        run: docker push harbor.bamiland.shop/myproject/myimage:${{ github.ref_name }}



