name: Build and Push to BamiHarbor

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: [self-hosted]

    steps:
      - name: Add host entry
        run: echo "34.64.249.38 harbor.bami.shop" | sudo tee -a /etc/hosts

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login http://harbor.bami.shop -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and Push
        run: |
          IMAGE_TAG=harbor.bami.shop/bami-ci-test/myimage:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
