name: Build and Push to BamiHarbor

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-push:
    name: Build Docker Image and Push to BamiHarbor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional, but good for multi-arch builds)
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | sudo docker login bami.harbor.com -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=harbor.registry.com/myproject/myimage:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker Image to Harbor
        run: |
          docker push $IMAGE_TAG
