name: Build and Push to Harbor

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: [self-hosted]

    steps:
      - name: Add harbor DNS to /etc/hosts
        run: |
          echo "34.64.249.38 harbor.bamiland.shop" >> /tmp/hosts_test
          cat /tmp/hosts_test



