name: Build and Push to Harbor

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          whoami
          groups
          docker info

      - name: Docker Login to Harbor
        run: |
          set -xe
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login https://harbor.bamiland.shop \
            -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          set -xe
          IMAGE_TAG=harbor.bamiland.shop/bami-ci-test/myapp:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker Image to Harbor
        run: |
          set -xe
          docker push $IMAGE_TAG

